/* Generated By:JavaCC: Do not edit this line. LTLParserConstants.java */
package rabinizer.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOP = 5;
  /** RegularExpression Id. */
  int GOP = 6;
  /** RegularExpression Id. */
  int XOP = 7;
  /** RegularExpression Id. */
  int NEG = 8;
  /** RegularExpression Id. */
  int UOP = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int LPAR = 12;
  /** RegularExpression Id. */
  int RPAR = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int ID = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"F\"",
    "\"G\"",
    "\"X\"",
    "\"!\"",
    "\"U\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "<TRUE>",
    "<FALSE>",
    "<ID>",
  };

}
