/* Generated By:JavaCC: Do not edit this line. NormParserConstants.java */
/* Insert the default contents of the file here.  May need imoprts etc.
*/
package normativeagents.parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NormParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOP = 5;
  /** RegularExpression Id. */
  int GOP = 6;
  /** RegularExpression Id. */
  int XOP = 7;
  /** RegularExpression Id. */
  int NEG = 8;
  /** RegularExpression Id. */
  int UOP = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int IMP = 12;
  /** RegularExpression Id. */
  int LPAR = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int COM = 15;
  /** RegularExpression Id. */
  int SEMI = 16;
  /** RegularExpression Id. */
  int COL = 17;
  /** RegularExpression Id. */
  int TRUE = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int NUM = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"F\"",
    "\"G\"",
    "\"X\"",
    "\"!\"",
    "\"U\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "<TRUE>",
    "<FALSE>",
    "<ID>",
    "<NUM>",
  };

}
